### ISSUE TITLE
Issue with output format

### ISSUE THREAD

**Issue by overthink** [YuryBecker/matching#1]
Hi Yury,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

i.e. there should be one line in your output for each product, with an associated list of matching listings.  Also, the format of the value in the `listings` field is incorrect -- it should be a list of listings objects.

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by YuryBecker** [comment]
Hi Mark, 
This was certainly an interesting challenge, but unfortunately at this time I would like to withdraw. 
Please feel free to use the code as you see fit.

For completeness sake, I changed the output results formatting to match yours (I had the output as just listing.values() instead of the json line.)

Thanks for looking!
Yury
